<Project>
  <PropertyGroup>
    <Version>2.2.3</Version>
    <FileVersion>2.2.3.0</FileVersion>
    <AssemblyVersion>2.2.3.0</AssemblyVersion>
    <InformationalVersion>2.2.3</InformationalVersion>
    <Authors>ANSH9BOSS</Authors>
    <Company>ANSH9BOSS</Company>
    <Product>VayuClient</Product>
    <Copyright>Copyright Â© 2026 ANSH9BOSS</Copyright>
  </PropertyGroup>
</Project>
