package com.vayuclient.ui.core;

public enum VayuCapability {
    CUSTOM_TITLE_SCREEN,
    CUSTOM_LOADING_SCREEN,
    GLASS_PANELS,
    ANIMATED_BACKGROUND,
    SCREEN_TRANSITIONS,
    CUSTOM_BUTTONS,
    CUSTOM_PAUSE_MENU,
    PARTICLE_EFFECTS,
    BLUR_FALLBACK
}
